trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'acr2'
    repository: 'lasyaacr'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'



