trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'acr2'
    repository: 'lasyaacr'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '01_kubernetes_aks'
- task: Docker@2
  inputs:
    containerRegistry: 'acr2'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'acr2'
    repository: 'lasyaacr'
    command: 'push'
    arguments: '01_kubernetes_aks'


